### PR TITLE
Improve naming of some functions

### PR DESCRIPTION
**Pull request by jonasnick**
~~Based on #37~~. WIP because we may find more improvements and it'd be better to bundle them in a single PR.

### CODE REVIEW

**Comment by real-or-random** [comment]
Concept ACK

**Comment by jonasnick** [comment]
If there are other things we should rename then let's do that in this PR.

**Comment by robot-dreams** [comment]
Concept ACK, all of these seem like improvements

**Comment by robot-dreams** [comment]
ACK

Nit: Is it worth swapping last two commits when rebasing for merge conflict?

**Comment by jonasnick** [comment]
> Nit: Is it worth swapping last two commits when rebasing for merge conflict?

done

**Pull request merged**
