### PR TITLE
Attempt at making algorithm headings more readable.

### PR DESCRIPTION
**Pull request by real-or-random**
What do you think of this? Is this an improvement?

Also supposed to solve #40.

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
Concept ACK, this is an improvement and I have no better idea for marking internal functions.

Regarding the "Promote algorithm sections" commit, previously my approach was that we'd have all the essential parts in a single section, namely "Description". But I prefer your commit, because it results in significantly nicer rendering.

**Comment by robot-dreams** [comment]
Concept ACK, agree that section headers are cleaner. The format is no longer consistent with BIP-340, but I doubt we want to worry about that.

Maybe an alternative approach to putting `Algorithm` or `Internal Algorithm` in front, could be to add a section called "Public API" and just list the function signatures that should be public.

**Comment by jonasnick** [comment]
> Maybe an alternative approach to putting Algorithm or Internal Algorithm in front, could be to add a section called "Public API" and just list the function signatures that should be public.

Interesting idea. I slightly prefer the `Algorithm/Internal Algorithm` variant because it doesn't require remembering or looking up the "Public API" when reading the actual functions. Perhaps do both? In any case, users (and not implementors) of the BIP who are only interested in the Public API probably find it more useful to read the public api of their implementation and not the BIP.

**Comment by jonasnick** [comment]
Superseded by #65

**Pull request closed without merging**
